"""
Meeting Prep Briefing — generates a one-page briefing for an investor call.

Usage:
    python briefing.py "Sarah Chen" "Sequoia Capital"
    python briefing.py "Sam Altman" "OpenAI"

Requires:
    pip install anthropic
    export ANTHROPIC_API_KEY=your-key

Generated by /build from product_requirements.md
"""

import sys
import os
from datetime import date
from pathlib import Path

import anthropic


def generate_briefing(person: str, company: str) -> str:
    """Research a person and company, return a structured markdown briefing."""
    client = anthropic.Anthropic()

    system_prompt = """You are a meeting prep researcher. Given a person and their company/fund,
produce a concise one-page briefing in markdown. Be specific and factual — no filler.

Format:
# Briefing: {Person Name} — {Company}
*Generated {date}*

## Person Overview
Role, background, investment focus or domain expertise, notable public takes or writing.

## Fund/Company Overview
Stage focus, sector focus, fund size (if known), recent notable deals or milestones.

## Recent News
3-5 bullet points from the last 6 months. Each with a one-line summary. Skip if nothing recent.

## Talking Points
3 specific conversation starters grounded in the research above. Not generic — reference
specific deals, posts, or news items. The kind of thing that shows you did your homework.

Rules:
- One page. If you can't fill a section with real information, say "No recent data found" — don't pad.
- Every fact should be verifiable from your web search results.
- Talking points must reference specific things from the research, not generic prompts.
- Use plain language. No corporate jargon."""

    with client.messages.stream(
        model="claude-sonnet-4-6",
        max_tokens=4096,
        system=system_prompt,
        tools=[
            {"type": "web_search_20260209", "name": "web_search"},
        ],
        messages=[
            {
                "role": "user",
                "content": f"Research {person} at {company} and generate my meeting prep briefing.",
            }
        ],
    ) as stream:
        response = stream.get_final_message()

    # Extract text from response blocks
    text_parts = []
    for block in response.content:
        if block.type == "text":
            text_parts.append(block.text)

    return "\n".join(text_parts)


def save_briefing(person: str, content: str) -> Path:
    """Save briefing to briefings/ directory."""
    briefings_dir = Path(__file__).parent / "briefings"
    briefings_dir.mkdir(exist_ok=True)

    safe_name = person.lower().replace(" ", "_")
    filename = f"{safe_name}_{date.today().isoformat()}.md"
    filepath = briefings_dir / filename

    filepath.write_text(content)
    return filepath


def main():
    if len(sys.argv) != 3:
        print("Usage: python briefing.py <person_name> <company_name>")
        print('Example: python briefing.py "Sarah Chen" "Sequoia Capital"')
        sys.exit(1)

    person = sys.argv[1]
    company = sys.argv[2]

    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("Error: ANTHROPIC_API_KEY environment variable not set.")
        print("Get your key at https://console.anthropic.com")
        sys.exit(1)

    print(f"Researching {person} at {company}...\n")

    briefing = generate_briefing(person, company)

    # Print to stdout
    print(briefing)

    # Save to file
    filepath = save_briefing(person, briefing)
    print(f"\n---\nSaved to {filepath}")


if __name__ == "__main__":
    main()
